version: '2'
volumes:
  db_data: {}
services:
  db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql/data
    environment:
      - MYSQL_ROOT_PASSWORD=passwd
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=phpvigo
  app:
    image: dibanez/phpvigo-php72
    ports:
      - 80:80
    volumes:
      - ./:/var/www/
    depends_on:
      - db
    links:
      - db
    environment:
      - MYSQL_SERVER=db
      - MYSQL_PASSWORD=pass
      - MYSQL_USER=user
